### ISSUE TITLE
[Bug] WindTools break WeakAuras 3.5.0

### ISSUE THREAD

**Issue by mrbuds** [fang2hou/ElvUI_WindTools#165]
**Describe the bug**
When using your addon WeakAuras doesn't work

![image](https://user-images.githubusercontent.com/189656/123894284-2ffa0600-d95e-11eb-86d8-730baa816f75.png)

For context, i'm one of the WeakAuras maintainers and we had a few reports of your addon breaking weakauras.

**Comment by fang2hou** [comment]
confirmed, fixing

**Comment by fang2hou** [comment]
Fixed in acf76931d59a0efb5bb279da13cbf5221a95ed0d

**Comment by mrbuds** [comment]
We are still getting a lot of reports on our discord, afaik the fixed version is still in alpha, we would like to tell our users to update your addon but we'd prefer not tell them to switch to alpha version.

**Comment by mrbuds** [comment]
I didn't see 2.2.0 was release since, thank you
