### ISSUE TITLE
[Bug] with the channel button for community

### ISSUE THREAD

**Issue by Johunn** [fang2hou/ElvUI_WindTools#259]
**Describe the bug**
I cannot use the channel button for a community. I tried with only Elvui & Windtools enabled, same thing.

**To Reproduce**
1. Add the channel of the community in my chat interface
2. Enable the community button and add the name of the channel in windtools
3. Click on the channel button for the community

 Message: ...ce/AddOns/ElvUI_WindTools/Modules/Social/ChatBar.lua:353: attempt to call method 'Log' (a nil value)
Time: Sat Nov 19 19:35:44 2022
Count: 1
Stack: ...ce/AddOns/ElvUI_WindTools/Modules/Social/ChatBar.lua:353: attempt to call method 'Log' (a nil value)
[string "=[C]"]: in function `Log'
[string "@Interface/AddOns/ElvUI_WindTools/Modules/Social/ChatBar.lua"]:353: in function <...ce/AddOns/ElvUI_WindTools/Modules/Social/ChatBar.lua:347>

Locals:  

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: [3.0.3]
 - ElvUI Version [13.04]
 - WoW Build [10.0.2.46702]

Thank you for your help.

**Comment by fang2hou** [comment]
fixed in 20b785d6

**Comment by Johunn** [comment]
I ve downloaded the alpha update "3.0.5-beta-1". And I don't have anymore the error message, but it still doesn't work :(...

![2022-11-21 02_33_31-World of Warcraft](https://user-images.githubusercontent.com/32527234/202942606-89d045de-d742-4b7a-b675-69b155b9b06a.png)

**Comment by fang2hou** [comment]
> @fang2hou  I ve downloaded the alpha update "3.0.5-beta-1". And I don't have anymore the error message, but it still doesn't work :(...
> 
> 
> 
> ![2022-11-21 02_33_31-World of Warcraft](https://user-images.githubusercontent.com/32527234/202942606-89d045de-d742-4b7a-b675-69b155b9b06a.png)
> 
> 

As the error message saying and the tips shown in chat bar configuration. You need to add community to your chat frame tab in Blizzard Communities UI. Open the community you want to bind, there is a button in the top right of Blizzard Communities UI, add it to your main chat, then WindTools can access the community.

**Comment by Johunn** [comment]
@fang2hou Yes I know... That's what I did... The 7 channel "RiPA" is the community channel, and I added it correctly in my chat frame tab (it's enable on the screenshot), then I enabled the community channel in the addon and put the same channel name (RiPA)... I don't understand why it doesn't work.

![2022-11-21 12_47_46-World of Warcraft](https://user-images.githubusercontent.com/32527234/203044151-7921e816-dd75-4ced-9f14-13f42108f4c2.png)

**Comment by fang2hou** [comment]
@Johunn Perhaps you are not using the FULL NAME of the community

**Comment by Johunn** [comment]
@fang2hou  I tried the entire name of the community too "RiP Ally", same thing :(...

**Comment by fang2hou** [comment]
@Johunn Go to my Discord if you have time, screen sharing is needed for this situation.

**Comment by Johunn** [comment]
@fang2hou Okay I found... This time, the problem is from an other addon, thanks for your help and the last update who solve the problem.
